import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className='p-4'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-16 justify-center items-center flex flex-1 flex-col min-h-screen'>
        <h1 className='text-[4rem] leading-6 m-0 text-center'>
          Welcome to <a className='no-underline hover:underline text-[#0070f3]' href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className='text-center my-16 leading-6 text-[1.5rem]'>
          Get started by editing{' '}
          <code className='bg-[#f0f0f0] p-3 rounded-md text-[1.1rem] font-mono'>pages/index.tsx</code>
        </p>

        <div className='flex items-center justify-center flex-wrap max-w-3xl'>
          <a
            href="https://nextjs.org/docs"
            className='m-4 p-6 text-left max-w-xs decoration-none text-inherit hover:text-[#0070f3] 
            border-solid border border-[#eaeaea] hover:border-[#0070f3] transition-colors duration-200'
          >
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a 
            href="https://nextjs.org/learn" 
            className='m-4 p-6 text-left max-w-xs decoration-none text-inherit hover:text-[#0070f3] 
            border-solid border border-[#eaeaea] hover:border-[#0070f3] transition-colors duration-200'
          >
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className='m-4 p-6 text-left max-w-xs decoration-none text-inherit hover:text-[#0070f3] 
            border-solid border border-[#eaeaea] hover:border-[#0070f3] transition-colors duration-200'
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className='m-4 p-6 text-left max-w-xs decoration-none text-inherit hover:text-[#0070f3] 
            border-solid border border-[#eaeaea] hover:border-[#0070f3] transition-colors duration-200'
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className='flex flex-1 py-8 border-t border-solid border-[#eaeaea]'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className='flex items-center justify-center flex-grow'
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
